name: CI
on:
  pull_request:
  push:
    branches: [ main, master ]
jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    env:
      QODO_API_KEY: ${{ secrets.QODO_API_KEY }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]

      - name: Run tests
        run: pytest

      - name: Run lint
        run: |
          ruff check .
          mypy app

      - name: Setup Node.js for Qodo
        if: ${{ github.event_name == 'pull_request' && env.QODO_API_KEY != '' }}
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Qodo Review
        if: ${{ github.event_name == 'pull_request' && env.QODO_API_KEY != '' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx -y @qodo/command review --pr ${{ github.event.pull_request.number }} --ci
