name: CI
on:
  pull_request:
  push:
    branches: [ main, master ]
jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      - name: Run tests
        run: pytest
      - name: Run lint
        run: |
          ruff check .
          mypy app
      - name: Qodo Review
        if: github.event_name == 'pull_request'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          # Install qodo CLI if not present
          if ! command -v qodo >/dev/null 2>&1; then
            pip install qodo-cli || true
          fi
          REVIEW_OUTPUT=$(qodo review --pr ${{ github.event.pull_request.number }} || true)
          echo "$REVIEW_OUTPUT"
          # Extract blocking flag: expects a JSON line like 'blocking: true/false' or JSON output
          BLOCKING=$(echo "$REVIEW_OUTPUT" | grep -i "blocking:" | awk -F: '{gsub(/ /,""); print tolower($2)}')
          if [ "$BLOCKING" = "true" ]; then
            echo "Qodo review marked this PR as blocking" >&2
            exit 1
          fi
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Qodo Command
        run: |
          if [ "latest" = "latest" ]; then
            npm install -g @qodo/command
          else
            npm install -g @qodo/command@latest
          fi
      - name: Run Qodo Command
        run: |
          QODO_CMD="qodo --ci"
          # Add the prompt at the end
          QODO_CMD="$QODO_CMD \"<command>\""
          echo "Running: $QODO_CMD"
          eval $QODO_CMD