name: CI
on:
  pull_request:
  push:
    branches: [ main, master ]
jobs:
  build-test-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      - name: Run tests
        run: pytest
      - name: Run lint
        run: |
          ruff check .
          mypy app
      - name: Install Node.js
        if: ${{ github.event_name == 'pull_request' && secrets.QODO_API_KEY != '' }}
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install Qodo Command
        if: ${{ github.event_name == 'pull_request' && secrets.QODO_API_KEY != '' }}
        run: |
          npm install -g @qodo/command
      - name: Run Qodo Command
        if: ${{ github.event_name == 'pull_request' && secrets.QODO_API_KEY != '' }}
        env:
          QODO_API_KEY: ${{ secrets.QODO_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          qodo review --pr ${{ github.event.pull_request.number }} --ci